# Generated by Django 4.2.1 on 2023-05-08 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInfo',
            fields=[
                ('appointment_info_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('article_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=30)),
                ('article', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('phone_nb', models.BigIntegerField()),
                ('payment_info', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Mikvah',
            fields=[
                ('mikvah_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('phone_nb1', models.CharField(max_length=20)),
                ('phone_nb2', models.CharField(blank=True, max_length=20)),
                ('open_at', models.TimeField(blank=True)),
                ('ashkenaz', models.BooleanField(default=False)),
                ('sefarad', models.BooleanField(default=False)),
                ('chabad', models.BooleanField(default=False)),
                ('address_nb', models.CharField(max_length=4)),
                ('address_st', models.CharField(max_length=40)),
                ('address_city', models.CharField(max_length=40)),
                ('address_state', models.CharField(max_length=20)),
                ('address_country', models.CharField(max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('payment_gateway_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_account', models.BooleanField(default=False)),
                ('bit', models.BooleanField(default=False)),
                ('cb', models.BooleanField(default=False)),
                ('paypal', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.client')),
            ],
        ),
        migrations.CreateModel(
            name='MikvahServices',
            fields=[
                ('service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(default='ILS', max_length=3)),
                ('service', models.CharField(max_length=20)),
                ('duration', models.DurationField(blank=True)),
                ('mikvah_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mikvah')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricPayment',
            fields=[
                ('historic_payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.appointmentinfo')),
                ('client_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.client')),
                ('payment_gateway_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.paymentgateway')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentServices',
            fields=[
                ('appointment_service_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('appointment_info_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.appointmentinfo')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mikvahservices')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.client'),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='mikvah_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mikvah'),
        ),
    ]
