# Generated by Django 4.2.1 on 2023-05-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikvah',
            name='latitude',
            field=models.CharField(default=0, max_length=48),
        ),
        migrations.AddField(
            model_name='mikvah',
            name='longitude',
            field=models.CharField(default=0, max_length=48),
        ),
    ]
