# Generated by Django 4.2.1 on 2023-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_mikvah_latitude_alter_mikvah_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikvah',
            name='latitude',
            field=models.CharField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='mikvah',
            name='longitude',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
