# Generated by Django 4.2.1 on 2023-05-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_mikvah_latitude_alter_mikvah_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mikvah',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mikvah',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
