# Generated by Django 4.2.1 on 2023-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_mikvah_latitude_alter_mikvah_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='mikvah',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
