# Generated by Django 4.2.1 on 2023-05-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_mikvah_latitude_alter_mikvah_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('beginning_time', models.TimeField()),
                ('duration', models.CharField(choices=[('1h', '1 hour'), ('30min', '30 minutes'), ('15min', '15 minutes')], max_length=10)),
                ('mikvah_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mikvah')),
            ],
        ),
        migrations.CreateModel(
            name='MikvahCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Monday'), ('tues', 'Tuesday'), ('wen', 'Wednesday'), ('thur', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10)),
                ('opening_time', models.TimeField(blank=True)),
                ('closing_time', models.TimeField(blank=True)),
                ('mikvah_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mikvah')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointmentinfo',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='appointmentinfo',
            name='mikvah_id',
        ),
        migrations.RemoveField(
            model_name='appointmentservices',
            name='appointment_info_id',
        ),
        migrations.RemoveField(
            model_name='appointmentservices',
            name='service_id',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.RemoveField(
            model_name='historicpayment',
            name='appointment_info_id',
        ),
        migrations.RemoveField(
            model_name='historicpayment',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='historicpayment',
            name='payment_gateway_id',
        ),
        migrations.RemoveField(
            model_name='mikvahservices',
            name='mikvah_id',
        ),
        migrations.RemoveField(
            model_name='paymentgateway',
            name='client_id',
        ),
        migrations.DeleteModel(
            name='AppointmentInfo',
        ),
        migrations.DeleteModel(
            name='AppointmentServices',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='HistoricPayment',
        ),
        migrations.DeleteModel(
            name='MikvahServices',
        ),
        migrations.DeleteModel(
            name='PaymentGateway',
        ),
    ]
