# Generated by Django 4.2.1 on 2023-06-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
