# Generated by Django 4.2.1 on 2023-06-18 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_appointment_ending_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField(blank=True)),
                ('closing_time', models.TimeField(blank=True)),
                ('slot_start', models.FloatField(blank=True, null=True)),
                ('slot_end', models.FloatField(blank=True, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mikvahcalendar')),
            ],
        ),
    ]
