# Generated by Django 4.2.1 on 2023-06-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_rename_day_slots_mikvah_calendar_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slots',
            unique_together={('mikvah_calendar', 'start_time', 'end_time')},
        ),
    ]
