# Generated by Django 4.2.1 on 2023-06-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_appointment2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment2',
            name='appointment_time',
        ),
        migrations.AddField(
            model_name='appointment2',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment2',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment2',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
