# Generated by Django 4.2.1 on 2023-06-22 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0017_remove_appointment2_appointment_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('start', models.TimeField(blank=True)),
                ('end', models.TimeField(blank=True)),
                ('mikvah', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='website.mikvah')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
