# Generated by Django 4.2.1 on 2023-07-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_appointment3_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment3',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
