# Generated by Django 4.2.1 on 2023-08-03 09:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_appointment3_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment3',
            name='mikvah_calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.mikvahcalendar'),
            preserve_default=False,
        ),
    ]
