# Generated by Django 4.2.1 on 2023-08-06 07:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0023_remove_appointment2_user_delete_appointment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointment3',
            new_name='Appointment',
        ),
    ]
